apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redis-replications.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: RedisReplication
    plural: redis-replications
    singular: redis-replication
    shortNames:
      - rrk
      - rrks
  versions:
  - name: v1
    served: true
    storage: true
    additionalPrinterColumns:
      - jsonPath: .status.master
        description: Current master's Pod name
        name: Master
        type: string
      - jsonPath: .status.replicas
        description: Current number of Redis instances
        name: Replicas
        type: integer
      - jsonPath: .spec.replicas
        description: Desired number of Redis instances
        name: Desired
        type: integer
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          spec:
            properties:
              affinity:
                description: Pod affinity
                type: object
              annotations:
                additionalProperties:
                  type: string
                description: Pod annotations
                type: object
              config:
                additionalProperties:
                  type: string
                description: 'custom redis settings, some settings will be filtered, since they are manged by the operator, check source for redis_config_params_filter'
                type: object
              imagePullSecrets:
                description: 'Pod ImagePullSecrets More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod'
                items:
                  type: object
                type: array
              initContainers:
                description: Pod initContainers
                items:
                  type: object
                type: array
              acls:
                additionalProperties:
                  properties:
                    commands:
                      type: array
                      description: list of commands to allow/deny, if empty, no commands will be allowed
                      items:
                        type: string
                        pattern: '^+'
                    keyPatterns:
                      type: array
                      description: list of key patterns to allow/deny, if empty, no keys will be allowed
                      items:
                        type: string
                        pattern: '^~'
                    pubsubPatterns:
                      type: array
                      description: list of pubsub patterns to allow/deny, if empty, no pubsub will be allowed
                      items:
                        type: string
                        pattern: '^&'
                    passwords:
                      type: array
                      items:
                        type: object
                        properties:
                          secretName:
                            description: Name if the secret in the same namespace
                            type: string
                          secretDataKey:
                            description: Key Name that holds the secret
                            type: string
                        required:
                          - secretName
                          - secretDataKey
                    userEnable:
                      description: enable or disable the user, defaults to False
                      type: boolean
                  type: object
                type: object
              priorityClassName:
                description: Pod priorityClassName
                type: string
              redis:
                description: Redis container specification
                properties:
                  image:
                    description: Image is a standard path for a Container image
                    type: string
                  resources:
                    description: Resources describes the compute resource requirements
                    type: object
                  securityContext:
                    description: SecurityContext holds security configuration that will
                      be applied to a container
                    type: object
                required:
                  - image
                type: object
              replicas:
                description: number of redis instances
                format: int32
                minimum: 3
                type: integer
              securityContext:
                description: Pod securityContext
                type: object
              serviceAccountName:
                description: 'Pod ServiceAccountName is the name of the ServiceAccount
                  to use to run this pod. More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/'
                type: string
              sideCarContainers:
                description: Pod initContainers
                items:
                  type: object
                type: array
              nodeSelector:
                additionalProperties:
                  type: string
                description: NodeSelector specifies a map of key-value pairs. For the
                  pod to be eligible to run on a node, the node must have each of the
                  indicated key-value pairs as labels.
                type: object
              tolerations:
                description: Pod tolerations
                items:
                  type: object
                type: array
            required:
              - replicas
              - redis
            type: object
          status:
            properties:
              master:
                description: Master is the current master's Pod name
                type: string
              replicas:
                description: Replicas is the number of active Redis instances in the
                  replication
                format: int64
                type: integer
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
          - spec
