# A demo custom resource for the Kopf example operators.
apiVersion: kopf.dev/v1
kind: RedisReplication
metadata:
  name: rrk-blarg
  labels:
    somelabel: somevalue
  annotations:
    someannotation: somevalue
spec:
  acls:
    fartss:
      passwords:
        - secretName: redis-replication-example
          secretDataKey: password
      commands:
        - '+@all'
      keyPatterns:
        - '~farts*'
      pubsubPatterns:
        - '&fartss*'
    admin:
      commands:
        - '+@all'
      keyPatterns:
        - '~*'
      pubsubPatterns:
        - '&*'
      passwords:
        - secretName: redis-replication-example
          secretDataKey: admin_password
      userEnable: true
  config:
    maxmemory: 512mb
    save: ''
  replicas: 3
  redis:
    image: redis:7.0.10
