# A demo custom resource for the Kopf example operators.
apiVersion: kopf.dev/v1
kind: RedisReplication
metadata:
  name: rrd-1
  labels:
    somelabel: somevalue
  annotations:
    someannotation: somevalue
spec:
  acls:
    farts:
      passwords:
        - secretName: redis-replication-example
          secretDataKey: password
      commands:
        - '+@all'
      keyPatterns:
        - '~farts*'
      pubsubPatterns:
        - '&fartss*'
    admin:
      commands:
        - '+@all'
      keyPatterns:
        - '~*'
      pubsubPatterns:
        - '&*'
      passwords:
        - secretName: redis-replication-example
          secretDataKey: admin_password
      userEnable: on
  config:
    maxmemory: 128mb
    save: ''
  replicas: 3
  redis:
    image: redis
  sideCarContainers:
    - name: redis-exporter
      image: oliver006/redis_exporter:v1.58.0
      ports:
        - name: metrics
          containerPort: 9121
          protocol: TCP
      env:
        - name: REDIS_USER
          value: admin
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-replication-example
              key: admin_password

---
apiVersion: v1
kind: Service
metadata:
  name: rrd-1-primary
  labels:
    RedisReplication: rrd-1
    RedisReplicationRole: Primary
spec:
  type: LoadBalancer
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: metrics
      port: 9121
      protocol: TCP
      targetPort: 9121
  selector:
    RedisReplication: rrd-1
    RedisReplicationRole: Primary
---
apiVersion: v1
kind: Service
metadata:
  name: rrd-1-secondary
  labels:
    RedisReplication: rrd-1
    RedisReplicationRole: Secondary
spec:
  type: LoadBalancer
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: metrics
      port: 9121
      protocol: TCP
      targetPort: 9121
  selector:
    RedisReplication: rrd-1
    RedisReplicationRole: Secondary
