# A demo custom resource for the Kopf example operators.
apiVersion: kopf.dev/v1
kind: RedisReplication
metadata:
  name: rrd-98
  labels:
    somelabel: somevalue
  annotations:
    someannotation: somevalue
spec:
  acls:
    farts:
      passwords:
        - secretName: redis-replication-example
          secretDataKey: password
      commands:
        - '+@all'
      keyPatterns:
        - '~farts*'
      pubsubPatterns:
        - '&fartss*'
    admin:
      commands:
        - '+@all'
      keyPatterns:
        - '~*'
      pubsubPatterns:
        - '&*'
      passwords:
        - secretName: redis-replication-example
          secretDataKey: admin_password
      userEnable: on
  config:
    maxmemory: 128mb
    save: ''
  replicas: 3
  redis:
    image: redis

---
apiVersion: v1
kind: Service
metadata:
  name: rrd-98-primary
  labels:
    RedisReplication: rrd-98
    RedisReplicationRole: Primary
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      protocol: TCP
  selector:
    RedisReplication: rrd-98
    RedisReplicationRole: Primary
---
apiVersion: v1
kind: Service
metadata:
  name: rrd-98-secondary
  labels:
    RedisReplication: rrd-98
    RedisReplicationRole: Secondary
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      protocol: TCP
  selector:
    RedisReplication: rrd-98
    RedisReplicationRole: Secondary
